osx_image: xcode8.2
language: objective-c

before_install:
- cd Example/
- xcodebuild  -sdk "iphonesimulator" -xcconfig Spitfire.xcconfig -configuration Release clean
- rm -rf ~/Library/Developer/Xcode/DerivedData
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/Spitfire.xcworkspace -scheme Spitfire-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,id=AD8E8C76-910E-437D-88C2-4D6F6EBE3355,OS=10.2' | xcpretty
- pod lib lint
